version: '3.8'

services:
  claude-pr:
    image: claude-code:fast
    build:
      context: .
      dockerfile: Dockerfile.fast
    volumes:
      - ../:/workspace
      - ~/.ssh:/home/claude/.ssh:ro
      - ~/.gitconfig:/home/claude/.gitconfig:ro
      - ${HOME}/settings:/home/claude/settings:ro
      - claude-cargo-cache:/home/claude/.cargo/registry
      - claude-npm-cache:/home/claude/.npm
      - claude-cache:/home/claude/.cache
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GIT_USER_NAME=${GIT_USER_NAME:-Igor Dvorkin}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL:-idvorkin@gmail.com}
      - AUTO_BRANCH=${BRANCH}
      - PR_TITLE=${PR_TITLE}
      - JEKYLL_PORT=${JEKYLL_PORT:-4000}
    working_dir: /workspace
    stdin_open: true
    tty: true
    network_mode: host  # For Jekyll server access
    init: true  # Proper signal handling

  # Quick command for creating PR with branch
  quick-pr:
    extends: claude-pr
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GIT_USER_NAME=${GIT_USER_NAME:-Igor Dvorkin}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL:-idvorkin@gmail.com}
      - AUTO_BRANCH=${BRANCH:-feature-$(date +%Y%m%d-%H%M%S)}
      - PR_TITLE=${PR_TITLE:-New Feature}
      - AUTO_CREATE_BRANCH=true
    
  # Run Claude Code directly
  claude:
    extends: claude-pr
    entrypoint: ["claude"]
    command: []

  # Interactive shell for debugging
  shell:
    extends: claude-pr
    entrypoint: ["/bin/bash"]
    command: []

  # Run tests
  test:
    extends: claude-pr
    entrypoint: ["/bin/bash", "-c"]
    command: ["cd /workspace && just js-validate && just fast-test"]

  # Jekyll server
  jekyll:
    extends: claude-pr
    entrypoint: ["/bin/bash", "-c"]
    command: ["cd /workspace && just jekyll-serve ${JEKYLL_PORT:-4000}"]
    ports:
      - "${JEKYLL_PORT:-4000}:${JEKYLL_PORT:-4000}"

volumes:
  claude-cargo-cache:
    driver: local
  claude-npm-cache:
    driver: local
  claude-cache:
    driver: local